// Auto-generated by WIG Dashboard Refresh — 2026-05-15T07:30:00-07:00
// Chart URLs sourced live from _Charts sheet tab
window.WIG_CHART_URLS = {
  1: "https://script.google.com/a/macros/instacart.com/s/AKfycbwgtJSq3UE3HH78Galq4Lgw-7DyXWhRRp3ra0HLdRX1ZI8orUr4Rb0R7_CB_jWxpZqz/exec",
  2: "https://script.google.com/a/macros/instacart.com/s/AKfycbztkhMdhjMl7z8iO8Ry-J74HnIkFmnJuTj1eYcqrMNPl0X1YFTgQNtL5rumGxdcjZTF/exec",
  3: "https://script.google.com/a/macros/instacart.com/s/AKfycbx8H3G5ovovvx8e5JDVdTxBLWwxBkup0yfKjGz7ShGRpE-8dTP1yC3WlaxsAB6oLETi/exec",
  4: "https://script.google.com/a/macros/instacart.com/s/AKfycbz21VzX39pUFqYZD3NjqwT3EARZ2K7aDd8-OYetGSItfoEBx-pnM304E8QEwN7qVaTC/exec?embedded=true",
  5: "https://script.google.com/a/macros/instacart.com/s/AKfycbwt427jAAtIRCvNTO6P7kQQx36_9PAUTyTkqyWAt0Vgh8EQ6FEftd1NmAXQa-cC6Wjf/exec",
  6: "https://script.google.com/a/macros/instacart.com/s/AKfycbyCN9c3q68Tg1DdOkr_F84um0RUA5G1rbYCRJRUYN_ragwNjBNaGZHlf2KhyfXegkrI4w/exec"
};
// Live pulls: JIRA (ETS-Internal) + Glean (ETS WIG Manager sheet).
// Runs 30 min before ETS WIG Huddle (Thu 8:00 AM PT).
// IMPORTANT: `wig-commitment` JIRA label STILL returns 0 results (5th consecutive week).
// Commitments below reconciled from Glean scoreboard snippet + carried forward from
// prior dashboard. Escalate label adoption at today's huddle — blockers to tracking velocity.
window.WIG_JIRA_DATA = {
  lastUpdated: "2026-05-15T07:30:00-07:00",
  dataNote: "JIRA `wig-commitment` label query returned 0 tickets — 5th consecutive week. Escalate label adoption at huddle. Commitments populated from Glean (ETS WIG Manager sheet) + previously-tracked items still in flight.",
  scoreboard: {
    asOf: "2026-05-15",
    weeksRemaining: 6,
    note: "Glean snapshot shows scoreboard movement this week (delta column populated). Published 'Score' column still reads prior values — table refresh appears to lag the change chart. Current scores below reflect the most recently published 'Score' column; deltas are from the 'Absolute Score Change vs Last Update' chart and indicate trend direction.",
    wigs: [
      { id: 1, name: "Jira Mgmt Process", lead: "Hassan",   score: 60.0, prior: 60.0, delta: +5.0,  pctChange: 20.00,  trend: "up" },
      { id: 2, name: "CSAT",              lead: "Nikita",   score: 75.0, prior: 75.0, delta: +4.0,  pctChange: 19.05,  trend: "up" },
      { id: 3, name: "Knowledge Mgmt",    lead: "Alicia",   score: 44.5, prior: 44.5, delta: +0.2,  pctChange: 5.26,   trend: "up-slow" },
      { id: 4, name: "Track Untracked",   lead: "Eric",     score: 66.3, prior: 66.3, delta: +4.0,  pctChange: 133.33, trend: "up" },
      { id: 5, name: "Sophistication",    lead: "Sunny",    score: 57.1, prior: 57.1, delta: +2.9,  pctChange: 2.90,   trend: "up-slow" },
      { id: 6, name: "Incident Mgmt",     lead: "Jonathan", score: 69.0, prior: 69.0, delta: 0.0,   pctChange: 0.00,   trend: "flat" }
    ]
  },
  commitments: {
    thisWeek: [
      { key: "ETS-300", summary: "Create IoT Deployments Dashboard", assignee: "Sahil Khan", status: "In Progress", priority: "P1", url: "https://instacart.atlassian.net/browse/ETS-300", wig: "WIG 1 (Jira Mgmt)" },
      { key: "ETS-10",  summary: "Caper ETS Bot Project", assignee: "Sahil Khan", status: "In Progress", priority: "P1", url: "https://instacart.atlassian.net/browse/ETS-10",  wig: "WIG 1 (Jira Mgmt)" },
      { key: "ETS-89",  summary: "Remaining Instacart Ads Ticket", assignee: "Niraj Patel", status: "Intake", priority: "P1", url: "https://instacart.atlassian.net/browse/ETS-89",  wig: "WIG 1 (Jira Mgmt)" },
      { key: "ETS-372", summary: "EBT Testing", assignee: "Sahil Khan", status: "In Progress", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-372", wig: "WIG 1 (Jira Mgmt)" },
      { key: "ETS-342", summary: "Add scoreboard onto metrics dashboard for WIG", assignee: "Sahil Khan", status: "Review/Validation", priority: "P3", url: "https://instacart.atlassian.net/browse/ETS-342", wig: "WIG 4 (Track Untracked)" },
      { key: "ETS-281", summary: "Create Feedback Form for KM WIG", assignee: "Gage Maher", status: "In Progress", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-281", wig: "WIG 3 (KM)" },
      { key: "ETS-318", summary: "Add per-week feedback form to capture clarity scores", assignee: "Gage Maher", status: "Intake", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-318", wig: "WIG 3 (KM)" },
      { key: "ETS-315", summary: "Add buddy-review checkpoint after Basic Training", assignee: "Gage Maher", status: "Intake", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-315", wig: "WIG 3 (KM)" },
      { key: "ETS-367", summary: "New On-Call Training Catalog", assignee: "Hayden Kim", status: "Intake", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-367", wig: "WIG 3 (KM)" },
      { key: "ETS-371", summary: "Catalog Oncall Training", assignee: "Nathan Abraham", status: "Intake", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-371", wig: "WIG 3 (KM)" }
    ],
    lastWeek: [
      { key: "ETS-374", summary: "WIG Scoreboard for CSAT WIG", assignee: "John Aba", status: "Done", priority: "—", url: "https://instacart.atlassian.net/browse/ETS-374", wig: "WIG 2 (CSAT)" },
      { key: "ETS-369", summary: "Review RRC for Costco", assignee: "Maryna Kostiuk", status: "Done", priority: "P4", url: "https://instacart.atlassian.net/browse/ETS-369", wig: "WIG 1 (Jira Mgmt)" },
      { key: "GLEAN",   summary: "WIG hub launched at emic0017.github.io/ets-wig-hub (MollyJo: 'stellar')", assignee: "Eric Morin", status: "Done", priority: "—", url: "https://emic0017.github.io/ets-wig-hub", wig: "WIG 4 (Track Untracked)" },
      { key: "GLEAN",   summary: "CSAT scoreboard built in Superblocks", assignee: "Nikita Patrachari", status: "Done", priority: "—", url: "", wig: "WIG 2 (CSAT)" },
      { key: "GLEAN",   summary: "Stalled-ticket alerting + SLA timer deployed", assignee: "Hassan", status: "Done", priority: "—", url: "", wig: "WIG 1 (Jira Mgmt)" }
    ]
  },
  risks: [
    { wig: "Process", note: "`wig-commitment` JIRA label STILL not adopted (5th consecutive week) — dashboard relies on Glean + manual reconciliation. Make this an agenda item at today's huddle; assign an owner to enforce it.", owner: "Eric / WIG leads" },
    { wig: "WIG 6 (Incident Mgmt)", note: "FLAT week — 0 movement on Jonathan's WIG. Only WIG not moving. Worth a check-in.", owner: "Jonathan" },
    { wig: "Scoreboard", note: "Published 'Score' column in WIG Manager sheet appears to lag the change chart. Verify with Nikita whether the sheet auto-updates on save.", owner: "Nikita / Eric" },
    { wig: "Dark Matter intake", note: "Intake bucket grew from 58→68 this week (+10). Unassigned count rose from 18→28 (+10). 28 unassigned tickets in Intake is the highest yet — triage needed.", owner: "Hassan" },
    { wig: "WIG 5 (Sophistication)", note: "DE-48397 still open — Mode data source missing SLA data (carried risk).", owner: "Sunny" },
    { wig: "Tooling", note: "PSOINT-4804 Simplify WIG scoreboard P2 still open; export-values blocker.", owner: "Hayden" },
    { wig: "Hygiene", note: "ETS-363 and ETS-364 are duplicates ('User Not Found' on order requests). Close one.", owner: "Niraj / Hassan" }
  ],
  darkMatter: {
    totalTickets: 100,
    delta: -2,
    byStatus: { "Intake": 68, "In Progress": 32 },
    byStatusNote: "Planning and Review/Validation buckets collapsed vs. last week — may reflect JIRA workflow state change or all 9 prev R/V+Planning tickets moved. Verify with Hassan.",
    byAssignee: {
      "Gage Maher": 27,
      "Niraj Patel": 16,
      "Eric Morin": 6,
      "Sahil Khan": 4,
      "Maryna Kostiuk": 4,
      "Gabriel Sliwowicz": 4,
      "Hayden Kim": 3,
      "Nandini Patel": 2,
      "Harshjot Gahunia": 2,
      "Bilal Rizvi": 2,
      "Nathan Abraham": 1,
      "Nikita Patrachari": 1,
      "Unassigned": 28
    },
    newSinceLastRun: [
      { key: "ETS-376", summary: "Test", status: "Done", note: "(test ticket — close)" },
      { key: "ETS-375", summary: "Create LTE finalized orders automation", status: "Intake", assignee: "Sahil Khan" },
      { key: "ETS-374", summary: "WIG Scoreboard for CSAT WIG", status: "Done", assignee: "John Aba" },
      { key: "ETS-373", summary: "Test", status: "Done", note: "(test ticket — close)" },
      { key: "ETS-372", summary: "EBT Testing", status: "In Progress", assignee: "Sahil Khan" },
      { key: "ETS-370", summary: "test", status: "Done", note: "(test ticket — close)" },
      { key: "ETS-369", summary: "Review RRC for Costco (closed)", status: "Done", assignee: "Maryna Kostiuk" }
    ],
    topTickets: [
      { key: "ETS-300", summary: "Create IoT Deployments Dashboard", status: "In Progress", assignee: "Sahil Khan", priority: "P1", url: "https://instacart.atlassian.net/browse/ETS-300" },
      { key: "ETS-10",  summary: "Caper ETS Bot Project", status: "In Progress", assignee: "Sahil Khan", priority: "P1", url: "https://instacart.atlassian.net/browse/ETS-10" },
      { key: "ETS-89",  summary: "Remaining Instacart Ads Ticket", status: "Intake", assignee: "Niraj Patel", priority: "P1", url: "https://instacart.atlassian.net/browse/ETS-89" },
      { key: "ETS-372", summary: "EBT Testing", status: "In Progress", assignee: "Sahil Khan", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-372" },
      { key: "ETS-371", summary: "Catalog Oncall Training", status: "Intake", assignee: "Nathan Abraham", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-371" },
      { key: "ETS-368", summary: "[Oncall Runbook] Bypass orders directed to register", status: "Intake", assignee: "Unassigned", priority: "—", url: "https://instacart.atlassian.net/browse/ETS-368" },
      { key: "ETS-367", summary: "New On-Call Training Catalog", status: "Intake", assignee: "Hayden Kim", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-367" },
      { key: "ETS-365", summary: "Shopper Chat: Screen Reader Issue", status: "Intake", assignee: "Unassigned", priority: "P4", url: "https://instacart.atlassian.net/browse/ETS-365" },
      { key: "ETS-364", summary: "ICC Response: 'User Not Found' (dup of ETS-363)", status: "Intake", assignee: "Unassigned", priority: "P3", url: "https://instacart.atlassian.net/browse/ETS-364" },
      { key: "ETS-362", summary: "Create Runbook for PSO-77086", status: "Intake", assignee: "Niraj Patel", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-362" },
      { key: "ETS-361", summary: "Create Runbook for PSO-78237", status: "Intake", assignee: "Niraj Patel", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-361" },
      { key: "ETS-358", summary: "Create Runbook for PSO-78673", status: "Intake", assignee: "Bilal Rizvi", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-358" },
      { key: "ETS-342", summary: "Add scoreboard onto metrics dashboard for WIG", status: "Review/Validation", assignee: "Sahil Khan", priority: "P3", url: "https://instacart.atlassian.net/browse/ETS-342" },
      { key: "ETS-318", summary: "Add per-week feedback form to capture clarity scores", status: "Intake", assignee: "Gage Maher", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-318" },
      { key: "ETS-315", summary: "Add buddy-review checkpoint after Basic Training", status: "Intake", assignee: "Gage Maher", priority: "P2", url: "https://instacart.atlassian.net/browse/ETS-315" }
    ]
  },
  avgScore: 70.0,
  meetingStats: {
    date: "5/15/2026", chair: "Sahil Khan", nextChair: "Madhuri Surve",
    attendeeCount: 10, totalInvited: 12, absent: ["Sunny", "Nandini"]
  },
  commitmentLog: {
    1: [
      {week:"5/8",  lag:"Evaluate SLA timer results. Complete single-click for FaaS. Stalled-ticket alerting rollout. Schedule workshop.", lead:"Schedule workshop and feedback session to introduce 1-click integration and stalled-tickets alerting."},
      {week:"5/1",  lag:"Created Mode report for problematic Eng teams (filterable by pod). Stalled-ticket automation deployed for Whitelabel & FaaS. Engineering escalation SLA timer deployed for pilot tickets.", lead:"Evaluate SLA timer results for all pods. Complete single-click workflow for FaaS. Stalled-ticket alerting for remaining pods. Schedule team workshop."},
      {week:"4/24", lag:"Complete stall ticket dashboard. Complete coding on automation of single click for POD.", lead:"Top 5 Eng teams stalling tickets (last 1.5 yrs). Get async update if meeting postponed."},
      {week:"4/17", lag:"Functioning URL for scoreboard. Streamlining doc published for ETS. Single-click automation for one component.", lead:"Complete stall ticket dashboard. Complete coding on automation of single click for POD."},
      {week:"4/10", lag:"1-click automation draft done (FaaS pod config). Streamlining escalation across channels. Scoreboard functional but needs hosting.", lead:"Functioning URL for scoreboard. Streamlining doc published for ETS. Finish single-click for one component."},
      {week:"4/2",  lag:"Improve the scoreboard and link. Sync with eng teams.", lead:"1-click automation draft (FaaS pod config done), streamlining escalation, scoreboard ready for linking."},
      {week:"3/27", lag:"Lock baseline/target for eng-caused breaches. Finalized breach dashboard.", lead:"Improve scoreboard and link. Sync with eng teams."},
      {week:"3/20", lag:"Phase 2 data collection kicked off: at-risk SLA dashboard built, engineering-delay breaches confirmed as main driver.", lead:"Lock baseline/target for engineering-caused breaches, finalize breach dashboard, agree on success measures."}
    ],
    2: [
      {week:"5/1",  lag:"Completed presentation. Brainstorming sessions with team. Scheduled stakeholder review for Wednesday.", lead:"Review presentation with stakeholders, gather feedback, work toward enabling CSAT survey."},
      {week:"4/24", lag:"Feedback-handling process built into framework. Held interactions with teams already using CSAT.", lead:"Preparing presentation outlining process for handling incoming responses."},
      {week:"4/17", lag:"Created enhanced scorecard version. Wrapped up CSAT email template with final edits.", lead:"Build the feedback-handling framework: define how positive, neutral, and negative CSAT responses will be managed."},
      {week:"4/10", lag:"Built CSAT using Superblocks, team giving demo.", lead:"Review data-sanity items needed (e.g. email template for collecting feedback)."},
      {week:"4/2",  lag:"Develop a clear and reliable method for tracking incoming survey responses.", lead:"Evaluate and report Claude and eazyBI against requirements. Select preferred tool for dashboard creation."},
      {week:"3/27", lag:"Reach out to JIRA team to implement the survey.", lead:"Develop a clear and reliable method for tracking incoming survey responses."},
      {week:"3/20", lag:"Questions finalised. Received responses on poll. Discussed with stakeholders.", lead:"Reach out to JIRA team to implement survey."}
    ],
    3: [
      {week:"5/1",  lag:"General ONB doc completed, feedback form drafted.", lead:"Finalize feedback form, apply documentation process to current docs."},
      {week:"4/24", lag:"Finalize gen onboarding doc, write/update 2 docs each, create revision request process doc.", lead:"Finish gen onboarding doc, develop feedback form for external input on doc guidelines."},
      {week:"4/17", lag:"Creating missing pages for general onboarding docs: etiquette, mandatory meetings, system access.", lead:"Finalize gen onboarding doc, write/update 2 docs each, create revision request process doc."},
      {week:"4/10", lag:"Meeting to review and finalize General onboarding doc. Finalize Documentation Guidelines. Review individual pod onboarding docs.", lead:"Creating missing pages for general onboarding documents."},
      {week:"4/2",  lag:"Continued work on documentation guidelines. ONB doco in progress.", lead:"Meeting Tuesday to review and finalize General onboarding doc. Finalize Documentation Guidelines."},
      {week:"3/27", lag:"Continued work on documentation guidelines. ONB doco in progress.", lead:"Continued work on first milestone (documentation guidelines)."},
      {week:"3/20", lag:"Milestones identified. Archiving and documentation process begun. Scoreboard submitted.", lead:"Continue work on first milestone (documentation guidelines)."}
    ],
    4: [
      {week:"5/1",  lag:"Working on new survey, promoting adoption, dashboard completed.", lead:"Survey to be published next week, metrics to be added to ETS weekly metrics, more adoption ideas."},
      {week:"4/24", lag:"Feedback integration post-prezo, monitoring team usage and fixing bugs. Starting to look at live metrics.", lead:"Working on new survey, promoting adoption, Superblocks dashboard."},
      {week:"4/17", lag:"Dogfooding continues. ETS prezo at weekly meeting. Metrics review.", lead:"Feedback integration post-prezo, monitoring team usage and fixing bugs."},
      {week:"4/10", lag:"Scoreboard still needs integration (Nikita helping), dogfooding, review decomm. of PSO-Int.", lead:"Dogfooding continues. ETS prezo next week. Metrics review."},
      {week:"4/2",  lag:"Revising milestones, integration scoreboard, more testing.", lead:"Scoreboard still needs integration, dogfooding, review decomm. of PSO-Int."},
      {week:"3/27", lag:"Scoreboard complete, ingestion methods built, metrics in beta.", lead:"Revising milestones, integration scoreboard, more testing."},
      {week:"3/20", lag:"Scoreboard linked. Presentation to ETS prepared. Metrics still under review. Dogfooding in PSO-Int.", lead:"ETS prezo in Thu team meeting. Plans to invite alpha testers. More scoreboard updates."}
    ],
    5: [
      {week:"5/1",  lag:"SLA compliance rate blocked — Mode data source missing SLA data. Health Index drafted as weighted average of Freshness, Completeness, Velocity.", lead:"Show SLA compliance rate on dashboard. Finalize Health Index parameters. Book meeting with Eric/Nikita."},
      {week:"4/24", lag:"All hands on deck for AHT breakdown. Pie chart previewed.", lead:"SLA compliance rate ready to merge. Health Index formula first draft."},
      {week:"4/17", lag:"Pod level AHT ready to sign off. ETS level AHT breakdown in progress.", lead:"All hands on deck for AHT breakdown (pie chart: ticket handling time across ETS, ENG, reporter)."},
      {week:"4/10", lag:"Vibe-coded scoreboard 1st draft. ETS-level AHT ready to sign off.", lead:"Pod-level AHT ready to sign off. ETS-level AHT breakdown query finalized."},
      {week:"4/2",  lag:"Confirmed Mode capability for dashboard. Explored Google Apps Script for scoreboard.", lead:"Vibe code scoreboard 1st draft. ETS level AHT ready to sign-off."},
      {week:"3/27", lag:"Continue to work on AHT and linkable scoreboard. Exploring Mode capacity.", lead:"Dashboard design, documentation of KPIs, scoreboard creative updates."}
    ],
    6: [
      {week:"5/1",  lag:"Finished one pager and template. Brainstormed automation ideas, documented and assigned them.", lead:"Starting to implement ideas, create subtasks to split work amongst team members."},
      {week:"4/24", lag:"Finished process training, tooling training, and incident training docs.", lead:"Brainstorm automation ideas/solutions — at least 1 idea per ticket, covering alert routing and incident tooling."},
      {week:"4/17", lag:"Reviewed Training docs, begun writing tools documentation. Documentation gap process written.", lead:"Finish Training docs for incident bot and oncall rotator. Finish process training for new oncall folks."},
      {week:"4/10", lag:"Scoreboard link working. Confirmed all drafts exist.", lead:"Begin reviewing Training documentation for oncall processes/incidents/tooling. Finish Checklist document."},
      {week:"4/2",  lag:"Draft the remaining 3 runbooks, stakeholder review, scoreboard link.", lead:"Scoreboard link working, confirm all drafts exist."},
      {week:"3/27", lag:"7 docs reviewed, 4 drafted. Stakeholder review.", lead:"Draft the remaining 3, stakeholder review, scoreboard link."},
      {week:"3/20", lag:"Runbooks identified, docs reviewed by individual team members.", lead:"Will be reviewed as a team this week. Iterating on more docs."}
    ]
  }
};
